title: Site

tabs:
  # Onglet Pages
  pages:
    label: Pages
    icon: page
    columns:
      left:
        width: 2/3
        sections:
          pages_principales:
            label: Pages principales
            type: pages
            layout: cards
            image:
              query: false
              ratio: 3/1
              back: "rgb(30, 233, 169)"
            text: "{{ page.intendedTemplate }}"
            templates:
              - home
              - services
              - contact

      right:
        width: 1/3
        sections:
          pages_systeme:
            label: Paramètres système
            type: pages
            layout: cards
            image:
              query: false
              ratio: 3/1
              back: "rgb(254, 226, 196)"
            text: "{{ page.title }}"
            templates:
              - footer
              - mentions-legales

          logo_site:
            type: fields
            fields:
              logo_separator:
                type: line

              menu_logo:
                label: Logo du site
                type: files
                multiple: false
                layout: list
                size: small
                help: "Affiche dans le menu (header)"

  # Onglet Design
  design:
    label: Design
    icon: palette
    columns:
      # Colonne de gauche - COULEURS
      - width: 1/2
        fields:
          colorsHeading:
            label: Couleurs du site
            type: headline

          colorPrimary:
            label: Couleur principale
            type: color
            default: "#2ECC71"

          colorSecondary:
            label: Couleur secondaire
            type: color
            default: "#3498DB"

          colorAccent:
            label: Couleur accent
            type: color
            default: "#F39C12"

          colorNeutralInfo:
            label: Blanc
            type: info
            text: "Fixe: #ffffff"
            width: 1/2

          colorDarkInfo:
            label: Noir
            type: info
            text: "Fixe: #000000"
            width: 1/2

          colorBackground:
            label: Couleur de fond
            type: color
            default: "#F5F5F5"

      # Colonne de droite - TYPOGRAPHIES
      - width: 1/2
        fields:
          typographyHeading:
            label: Typographies
            type: headline

          fontPrimary:
            label: Typographie principale (titres)
            type: url
            placeholder: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
            help: "Lien Google Fonts pour les titres"

          fontSecondary:
            label: Typographie secondaire (texte)
            type: url
            placeholder: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap"
            help: "Lien Google Fonts pour le corps de texte"

  # Onglet SEO
  seo:
    extends: seo/site

  # Onglet Cookies
  cookies:
    label: Cookies
    icon: shield
    columns:
      - width: 1/1
        fields:
          cookieBannerHeading:
            label: Bandeau cookies
            type: headline

          cookieBannerEnabled:
            label: Afficher le bandeau
            type: toggle
            default: true

          cookieBannerText:
            label: Texte
            type: writer
            inline: true
            marks: [bold, link]
            help: "Message affiche dans le bandeau cookies"

          cookieBannerAcceptLabel:
            label: Bouton accepter
            type: text
            default: "Accepter"

          cookieBannerDeclineLabel:
            label: Bouton refuser (optionnel)
            type: text
            default: "Refuser"

          cookieBannerLinkLabel:
            label: Lien politique
            type: text
            default: "Politique de confidentialite"

          cookieBannerLinkUrl:
            label: URL politique
            type: url
            placeholder: "https://example.com/politique-de-confidentialite"
